# Generated by Django 3.2.15 on 2022-10-03 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricante',
            name='localizacao',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Localização'),
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('preco', models.FloatField(blank=True, null=True, verbose_name='Preço')),
                ('taxaEnvio', models.FloatField(blank=True, null=True, verbose_name='Taxa de envio')),
                ('qtdade', models.IntegerField(blank=True, null=True, verbose_name='Quantidade')),
                ('fabricante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.fabricante')),
            ],
        ),
    ]
