# Generated by Django 4.2 on 2023-05-07 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_produtorrural_propriedaderural'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtorrural',
            name='cpf',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='propriedaderural',
            name='produtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.produtorrural'),
        ),
    ]
