# Generated by Django 4.2 on 2023-07-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_produto_fabricante_produtorrural_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedaderural',
            name='endereco',
            field=models.CharField(default='endereço', max_length=100),
        ),
        migrations.AddField(
            model_name='propriedaderural',
            name='latitude',
            field=models.CharField(default='latitude', max_length=100),
        ),
        migrations.AddField(
            model_name='propriedaderural',
            name='longitude',
            field=models.CharField(default='longitude', max_length=100),
        ),
    ]
