# Generated by Django 4.2 on 2023-07-25 12:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_propriedaderural_endereco_propriedaderural_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeRaca', models.CharField(default='raça padrao', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeLote', models.CharField(default='lote padrao', max_length=100)),
                ('idProp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.propriedaderural')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoesRaca', models.CharField(default='observaçoes padrao', max_length=100)),
                ('sexo', models.CharField(default='padrao', max_length=100)),
                ('peso', models.FloatField(default='0.0')),
                ('dataNascimento', models.DateField(default=datetime.date.today)),
                ('dataMorte', models.DateField(default=datetime.date.today)),
                ('observacoes', models.CharField(default='padrao', max_length=100)),
                ('rfid', models.CharField(default='padrao', max_length=100)),
                ('brinco', models.CharField(default='padrao', max_length=100)),
                ('idAnimalMae', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.animal')),
                ('idLote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lote')),
                ('idProp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.propriedaderural')),
                ('idRaca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.raca')),
            ],
        ),
    ]
