# Generated by Django 4.2 on 2023-08-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_raca_lote_animal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='nome padrao', max_length=100)),
                ('telefone', models.CharField(default='telefone padrao', max_length=100)),
                ('email', models.CharField(default='email padrao', max_length=100)),
                ('crmv', models.CharField(default='crm padrao', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='animal',
            name='brinco',
            field=models.CharField(default='padrão', max_length=100),
        ),
        migrations.AlterField(
            model_name='animal',
            name='observacoes',
            field=models.CharField(default='padrão', max_length=100),
        ),
        migrations.AlterField(
            model_name='animal',
            name='observacoesRaca',
            field=models.CharField(default='padrão', max_length=100),
        ),
        migrations.AlterField(
            model_name='animal',
            name='rfid',
            field=models.CharField(default='padrão', max_length=100),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(default='padrão', max_length=100),
        ),
    ]
