# Generated by Django 4.2 on 2023-08-10 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_compraranimal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocorrencia', models.CharField(default='Padrao', max_length=100)),
                ('idAnimal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.animal')),
            ],
        ),
    ]
