# Generated by Django 4.2 on 2023-10-08 17:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_inseminacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricaoMovimentacao', models.CharField(default='Padrao', max_length=100)),
                ('dataMovimentacao', models.DateField(default=datetime.date.today)),
                ('idAnimal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.animal')),
                ('idLoteDestino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_destino', to='core.lote')),
                ('idLoteOrigem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_origem', to='core.lote')),
            ],
        ),
    ]
