# Generated by Django 4.2 on 2023-10-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_movimentacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoAlimenticio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProdutoAlimenticio', models.CharField(default='Padrao', max_length=100)),
                ('tipoProdutoAlimenticio', models.CharField(default='Padrao', max_length=100)),
            ],
        ),
    ]
