# Generated by Django 4.2 on 2023-10-11 00:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_produtoalimenticio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suplementacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kgConsumoSuplementacao', models.FloatField(default='0.0')),
                ('dataAplicacaoSuplementacao', models.DateField(default=datetime.date.today)),
                ('idLoteSuplAplicado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lote')),
                ('idProdutoAlimenticio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.produtoalimenticio')),
            ],
        ),
    ]
