# Generated by Django 4.2 on 2023-10-14 04:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_suplementacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField(default='0.0')),
                ('dataPesagem', models.DateField(default=datetime.date.today)),
                ('idAnimal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.animal')),
            ],
        ),
    ]
