# Generated by Django 4.2 on 2023-10-15 17:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_pesagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutraDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataDespesa', models.DateField(default=datetime.date.today)),
                ('descricaoOutraDespesa', models.CharField(default='Padrao', max_length=100)),
                ('valorOutraDespesa', models.FloatField(default='0.0')),
                ('idPropOutraDespesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.propriedaderural')),
            ],
        ),
    ]
