# Generated by Django 4.2 on 2023-10-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_outradespesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedaderural',
            name='tamanhoAreaProducao',
            field=models.CharField(default='Padrao', max_length=100),
        ),
        migrations.AlterField(
            model_name='produtorrural',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='produtorrural',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
