# Generated by Django 4.2 on 2023-10-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_propriedaderural_tamanhoareaproducao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='animal_Pai',
            field=models.CharField(default='padrão', max_length=100),
        ),
        migrations.AddField(
            model_name='animal',
            name='numeroGestacoes',
            field=models.IntegerField(default='0'),
        ),
    ]
