# Generated by Django 4.2 on 2023-10-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_descricaomovimentacao_movimentacao_motivomovimentacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='tipoCultivo',
            field=models.CharField(default='lote padrao', max_length=100),
        ),
    ]
