# Generated by Django 4.2 on 2023-10-24 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_outradespesa_motivogasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='dataRecebimento',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
