# Generated by Django 4.2 on 2023-10-25 12:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_venda_datarecebimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='AplicarProdutoSanitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataAplicacao', models.DateField(default=datetime.date.today)),
                ('dosagem', models.CharField(default='Padrao', max_length=100)),
                ('observacao', models.CharField(default='Padrao', max_length=100)),
                ('idAnimal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.animal')),
                ('idProduto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.prodsanitario')),
            ],
        ),
    ]
