# Generated by Django 4.2 on 2023-10-25 14:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_aplicarprodutosanitario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraProdutos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorUnitario', models.FloatField(default='0.0')),
                ('qtdComprada', models.IntegerField(default='0')),
                ('dataCompra', models.DateField(default=datetime.date.today)),
                ('descricao', models.CharField(default='Padrao', max_length=100)),
                ('valorTotal', models.FloatField(default='0.0')),
                ('validade', models.DateField(default=datetime.date.today)),
                ('idProduto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.prodsanitario')),
            ],
        ),
    ]
