# Generated by Django 4.2 on 2023-10-25 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_compraprodutos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prodsanitario',
            old_name='nomeProdSanitario',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='produtoalimenticio',
            old_name='nomeProdutoAlimenticio',
            new_name='nome',
        ),
    ]
